name: Build and Push Image to GHCR

on:
  push:
    branches: [ main ]
  release:
    types: [published]
  schedule:
    - cron: '0 0 * * 0'

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push-all:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push all flavors
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./all.Dockerfile
          outputs: type=local,dest=./out
          push: true
          build-args: |
            "FLAVOR=${{ matrix.flavor }}"
          tags: |
            ghcr.io/${{ github.repository }}:${{ matrix.flavor }}
          cache-from: type=registry,ref=ghcr.io/${{ github.repository }}:buildcache
          cache-to: type=registry,ref=ghcr.io/${{ github.repository }}:buildcache,mode=max
          #platforms: linux/amd64,linux/arm64
      - name: tar the release
        id: tar
        run: |
          TAR="$(basename "${{ github.repository }}")-${{ github.ref_name }}".tgz
          tar -zcvf "${TAR}" ./out
          echo tarball="${TAR}" | tee "${GITHUB_OUTPUT}"
        if: github.ref_type == 'tag'
      #- name: Setup upterm session
      #  uses: owenthereal/action-upterm@v1
      #  with:
      #    limit-access-to-users: 'b-' # Specific authorized users only
      - name: Release
        if: github.ref_type == 'tag'
        uses: softprops/action-gh-release@v2
        with:
          files: "${{ steps.tar.outputs.tarball }}"
  build-and-push-flavors:
    needs: [ build-and-push-all ]
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    strategy:
      fail-fast: true
      matrix:
        flavor:
          - catppuccin-frappe
          - catppuccin-macchiato
          - catppuccin-latte
          - catppuccin-mocha
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push individual flavors
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./all.Dockerfile
          outputs: type=local,dest=./out
          push: true
          build-args: |
            "FLAVOR=${{ matrix.flavor }}"
          tags: |
            ghcr.io/${{ github.repository }}:${{ matrix.flavor }}
          cache-from: type=registry,ref=ghcr.io/${{ github.repository }}:buildcache
          cache-to: type=registry,ref=ghcr.io/${{ github.repository }}:buildcache,mode=max
          #platforms: linux/amd64,linux/arm64
      - name: tar the release
        id: tar
        run: |
          TAR="$(basename "${{ github.repository }}")-${{ github.ref_name }}".tgz
          tar -zcvf "${TAR}" ./out
          echo tarball="${TAR}" | tee "${GITHUB_OUTPUT}"
        if: github.ref_type == 'tag'
      #- name: Setup upterm session
      #  uses: owenthereal/action-upterm@v1
      #  with:
      #    limit-access-to-users: 'b-' # Specific authorized users only
      - name: Release
        if: github.ref_type == 'tag'
        uses: softprops/action-gh-release@v2
        with:
          files: "${{ steps.tar.outputs.tarball }}"
